# Generated by Django 3.2.6 on 2021-09-13 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermart', '0002_auto_20210913_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='productCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='supermart.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermart.subcategory'),
        ),
    ]
