# Generated by Django 3.2.6 on 2021-09-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supermart', '0003_auto_20210913_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
