# Generated by Django 3.2.6 on 2021-09-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supermart', '0004_remove_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
